// components
export { default as Background } from './Background'
export { default as BasicCustomerFooter } from './BasicCustomerFooter'
export { default as BasicFooter } from './BasicFooter'
export { default as Body } from './Body'
export { default as Button } from './Button'
export { default as Footer } from './Footer'
export { default as Form } from './Form'
export { default as Header } from './Header'
export { default as Link } from './Link'
export { default as Screen } from './Screen'
export { default as OrderTable } from './OrderTable'
export { default as Order } from './Order'

// images
export { default as backgroundImage } from './background.png'
export { default as bagelShopImage } from './bagelShop.jpg'
export { default as bagelWithSmearImage } from './bagelWithSmear.jpg'
export { default as cartImage } from './cart.jpg'
export { default as logoImage } from './logo.png'
export { default as manImage } from './man.png'
export { default as moreBagelsImage } from './moreBagels.jpg'
export { default as scoobyImage } from './scooby.png'
export { default as yumBagelImage } from './yumBagel.jpg'
