const default_inventory = [
  [
  {category: "BAGEL"},
  {name: "Plain"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "BAGEL"},
  {name: "Onion"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "BAGEL"},
  {name: "Cinnamon raisin"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "BAGEL"},
  {name: "Sesame"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "BAGEL"},
  {name: "Cheesy"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "BAGEL"},
  {name: "Pumpernickel"},
  {qty: 0},
  {price: 2},
    ],
  [
  {category: "SMEAR"},
  {name: "Plain"},
  {qty: 0},
  {price: 1},      
    ],
  [
  {category: "SMEAR"},
  {name: "Honey_nut"},
  {qty: 0},
  {price: 1},      
    ],
  [
  {category: "SMEAR"},
  {name: "Strawberry"},
  {qty: 0},
  {price: 1},      
    ],
  [
  {category: "SMEAR"},
  {name: "French_onion"},
  {qty: 0},
  {price: 1},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Bacon"},
  {qty: 0},
  {price: 1},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Egg"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Cheese"},
  {qty: 0},
  {price: 1},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Sausage"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Avocado"},
  {qty: 0},
  {price: 10},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Turkey"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Ham"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Spinach"},
  {qty: 0},
  {price: 1},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Tomato"},
  {qty: 0},
  {price: 1},
  ],
  [
  {category: "SAMMICHE_TOPPINGS"},
  {name: "Lox"},
  {qty: 0},
  {price: 10},
  ],
  [
  {category: "BEVERAGE"},
  {name: "Coffee"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "BEVERAGE"},
  {name: "Milk"},
  {qty: 0},
  {price: 2},
  ],
  [
  {category: "BEVERAGE"},
  {name: "OJ"},
  {qty: 0},
  {price: 2},
    ],
  [
  {category: "BEVERAGE"},
  {name: "Water"},
  {qty: 0},
  {price: 5},
  ]
]

