export const ROLES = {
	CUSTOMER: 'CUSTOMER',
	CASHIER: 'CASHIER',
	CHEF: 'CHEF',
	MANAGER: 'MANAGER',
	ADMIN: 'ADMIN',
}

export const ROLES_ENUM: $Keys<typeof ROLES>[] = Object.keys(ROLES)

export const INVENTORY_ITEM_CATEGORIES = {
	BEVERAGE: 'BEVERAGE',
	SAMMICHE_TOPPINGS: 'SAMMICHE_TOPPINGS',
	SMEAR: 'SMEAR',
	BAGEL: 'BAGEL',
}

export const INVENTORY_ITEM_CATEGORIES_ENUM: Array<
	$Keys<typeof INVENTORY_ITEM_CATEGORIES>
> = Object.keys(INVENTORY_ITEM_CATEGORIES)

export const ORDER_STATUS = {
	PLACED: 'PLACED',
	PREPARING: 'PREPARING',
	PREPARED: 'PREPARED',
	FULFILLED: 'FULFILLED',
	CANCELED: 'CANCELED',
	DID_NOT_PICK_UP: 'DID_NOT_PICK_UP',
}

export const ORDER_STATUS_ENUM: Array<$Keys<typeof ORDER_STATUS>> = Object.keys(
	ORDER_STATUS
)

const ONE_SECOND = 1000 // ms
const ONE_MINUTE = 60 * ONE_SECOND

export const PREPARING_UPDATE_RATE = 30 * ONE_SECOND

export const PREPARING_BEFORE_PICKUP = 15 * ONE_MINUTE
