export const ROLES = {
	CUSTOMER: 'CUSTOMER',
	CASHIER: 'CASHIER',
	CHEF: 'CHEF',
	MANAGER: 'MANAGER',
	ADMIN: 'ADMIN',
}

export const ROLES_ENUM: $Keys<typeof ROLES>[] = Object.keys(ROLES)

export const INVENTORY_ITEM_CATEGORIES = {
	BEVERAGE: 'BEVERAGE',
	SAMMICHE_TOPPINGS: 'SAMMICHE_TOPPINGS',
	SMEAR: 'SMEAR',
	BAGEL: 'BAGEL',
}

export const INVENTORY_ITEM_CATEGORIES_ENUM: Array<
	$Keys<typeof INVENTORY_ITEM_CATEGORIES>
> = Object.keys(INVENTORY_ITEM_CATEGORIES)
