// flow-typed signature: 681c4223529b59a4a6a77f27196d72df
// flow-typed version: <<STUB>>/connect-mongo_v^2.0.3/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-mongo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-mongo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-mongo/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-mongo/index' {
  declare module.exports: $Exports<'connect-mongo'>;
}
declare module 'connect-mongo/index.js' {
  declare module.exports: $Exports<'connect-mongo'>;
}
declare module 'connect-mongo/src/index' {
  declare module.exports: $Exports<'connect-mongo/src'>;
}
declare module 'connect-mongo/src/index.js' {
  declare module.exports: $Exports<'connect-mongo/src'>;
}
