// flow-typed signature: 1350319cf50bb460905c0beb65986828
// flow-typed version: <<STUB>>/http_v^0.0.1-security/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
