// flow-typed signature: a2c8cb9d3520d172148a9c91b9bdb8a9
// flow-typed version: <<STUB>>/mongoose-beautiful-unique-validation_v^7.1.1/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-beautiful-unique-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-beautiful-unique-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-beautiful-unique-validation/tests' {
  declare module.exports: any;
}

declare module 'mongoose-beautiful-unique-validation/tests/save' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-beautiful-unique-validation/index' {
  declare module.exports: $Exports<'mongoose-beautiful-unique-validation'>;
}
declare module 'mongoose-beautiful-unique-validation/index.js' {
  declare module.exports: $Exports<'mongoose-beautiful-unique-validation'>;
}
declare module 'mongoose-beautiful-unique-validation/tests/index' {
  declare module.exports: $Exports<'mongoose-beautiful-unique-validation/tests'>;
}
declare module 'mongoose-beautiful-unique-validation/tests/index.js' {
  declare module.exports: $Exports<'mongoose-beautiful-unique-validation/tests'>;
}
declare module 'mongoose-beautiful-unique-validation/tests/save.js' {
  declare module.exports: $Exports<'mongoose-beautiful-unique-validation/tests/save'>;
}
