// flow-typed signature: da01cdcc2d77801acdc7c3376943b948
// flow-typed version: <<STUB>>/mongoose-lean-defaults_v^0.3.1/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-lean-defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-lean-defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-lean-defaults/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'mongoose-lean-defaults/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-lean-defaults/__tests__/index.spec.js' {
  declare module.exports: $Exports<'mongoose-lean-defaults/__tests__/index.spec'>;
}
declare module 'mongoose-lean-defaults/index' {
  declare module.exports: $Exports<'mongoose-lean-defaults'>;
}
declare module 'mongoose-lean-defaults/index.js' {
  declare module.exports: $Exports<'mongoose-lean-defaults'>;
}
declare module 'mongoose-lean-defaults/jest.config.js' {
  declare module.exports: $Exports<'mongoose-lean-defaults/jest.config'>;
}
