// flow-typed signature: 0fbf6add9dc68e9c810196ced9646180
// flow-typed version: <<STUB>>/mongoose-lean-getters_v^0.1.1/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-lean-getters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-lean-getters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-lean-getters/test/examples.test' {
  declare module.exports: any;
}

declare module 'mongoose-lean-getters/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-lean-getters/index' {
  declare module.exports: $Exports<'mongoose-lean-getters'>;
}
declare module 'mongoose-lean-getters/index.js' {
  declare module.exports: $Exports<'mongoose-lean-getters'>;
}
declare module 'mongoose-lean-getters/test/examples.test.js' {
  declare module.exports: $Exports<'mongoose-lean-getters/test/examples.test'>;
}
declare module 'mongoose-lean-getters/test/index.test.js' {
  declare module.exports: $Exports<'mongoose-lean-getters/test/index.test'>;
}
