// flow-typed signature: 8ac5b573b65ddf739b5780602937fd50
// flow-typed version: <<STUB>>/passport-local-mongoose_v^6.0.1/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-local-mongoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-local-mongoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-local-mongoose/lib/authenticate' {
  declare module.exports: any;
}

declare module 'passport-local-mongoose/lib/errors' {
  declare module.exports: any;
}

declare module 'passport-local-mongoose/lib/pbkdf2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-local-mongoose/index' {
  declare module.exports: $Exports<'passport-local-mongoose'>;
}
declare module 'passport-local-mongoose/index.js' {
  declare module.exports: $Exports<'passport-local-mongoose'>;
}
declare module 'passport-local-mongoose/lib/authenticate.js' {
  declare module.exports: $Exports<'passport-local-mongoose/lib/authenticate'>;
}
declare module 'passport-local-mongoose/lib/errors.js' {
  declare module.exports: $Exports<'passport-local-mongoose/lib/errors'>;
}
declare module 'passport-local-mongoose/lib/pbkdf2.js' {
  declare module.exports: $Exports<'passport-local-mongoose/lib/pbkdf2'>;
}
