import type { InventoryItemSentToServer } from '../../types'

export const DEFAULT_INVENTORY: InventoryItemSentToServer[] = [
	{ name: 'Plain', category: 'BAGEL', quantity: 100, price: 200, onMenu: true, targetCount: 50 },
	{ name: 'Onion', category: 'BAGEL', quantity: 100, price: 200, onMenu: true, targetCount: 50 },
	{
		name: 'Cinnamon raisin',
		category: 'BAGEL',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{ name: 'Sesame', category: 'BAGEL', quantity: 100, price: 200, onMenu: true, targetCount: 50 },
	{ name: 'Cheesy', category: 'BAGEL', quantity: 100, price: 200, onMenu: true, targetCount: 50 },
	{
		name: 'Pumpernickel',
		category: 'BAGEL',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{ name: 'Plain', category: 'SMEAR', quantity: 100, price: 100, onMenu: true, targetCount: 50 },
	{
		name: 'Honey Nut',
		category: 'SMEAR',
		quantity: 100,
		price: 100,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Strawberry',
		category: 'SMEAR',
		quantity: 100,
		price: 100,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'French Onion',
		category: 'SMEAR',
		quantity: 100,
		price: 100,
		onMenu: true,
		targetCount: 50,
	},

	{
		name: 'Bacon',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 100,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Egg',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Cheese',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 100,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Sausage',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Avocado',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 1000,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Turkey',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Ham',
		category: 'SAMMICHE TOPPINGS',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Spinach',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 100,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Tomato',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 100,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Lox',
		category: 'SAMMICHE_TOPPINGS',
		quantity: 100,
		price: 1000,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Coffee',
		category: 'BEVERAGE',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{
		name: 'Milk',
		category: 'BEVERAGE',
		quantity: 100,
		price: 200,
		onMenu: true,
		targetCount: 50,
	},
	{ name: 'OJ', category: 'BEVERAGE', quantity: 100, price: 200, onMenu: true, targetCount: 50 },
	{
		name: 'Water',
		category: 'BEVERAGE',
		quantity: 100,
		price: 500,
		onMenu: true,
		targetCount: 50,
	},
]
