// flow-typed signature: e17b9ca7adc08876db75e8304dedb94d
// flow-typed version: <<STUB>>/@shelf/jest-mongodb_v^1.2.3/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shelf/jest-mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shelf/jest-mongodb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shelf/jest-mongodb/environment' {
  declare module.exports: any;
}

declare module '@shelf/jest-mongodb/jest-mongodb-config' {
  declare module.exports: any;
}

declare module '@shelf/jest-mongodb/jest-preset' {
  declare module.exports: any;
}

declare module '@shelf/jest-mongodb/mongo-aggregate.test' {
  declare module.exports: any;
}

declare module '@shelf/jest-mongodb/mongo-insert.test' {
  declare module.exports: any;
}

declare module '@shelf/jest-mongodb/setup' {
  declare module.exports: any;
}

declare module '@shelf/jest-mongodb/teardown' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shelf/jest-mongodb/environment.js' {
  declare module.exports: $Exports<'@shelf/jest-mongodb/environment'>;
}
declare module '@shelf/jest-mongodb/jest-mongodb-config.js' {
  declare module.exports: $Exports<'@shelf/jest-mongodb/jest-mongodb-config'>;
}
declare module '@shelf/jest-mongodb/jest-preset.js' {
  declare module.exports: $Exports<'@shelf/jest-mongodb/jest-preset'>;
}
declare module '@shelf/jest-mongodb/mongo-aggregate.test.js' {
  declare module.exports: $Exports<'@shelf/jest-mongodb/mongo-aggregate.test'>;
}
declare module '@shelf/jest-mongodb/mongo-insert.test.js' {
  declare module.exports: $Exports<'@shelf/jest-mongodb/mongo-insert.test'>;
}
declare module '@shelf/jest-mongodb/setup.js' {
  declare module.exports: $Exports<'@shelf/jest-mongodb/setup'>;
}
declare module '@shelf/jest-mongodb/teardown.js' {
  declare module.exports: $Exports<'@shelf/jest-mongodb/teardown'>;
}
