// flow-typed signature: c202b3496d4e30a39d22e2f957ec8b0f
// flow-typed version: <<STUB>>/react-query_v^2.22.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-query' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-query/dist/hydration/react-query-hydration.development' {
  declare module.exports: any;
}

declare module 'react-query/dist/hydration/react-query-hydration.production.min' {
  declare module.exports: any;
}

declare module 'react-query/dist/react-query.development' {
  declare module.exports: any;
}

declare module 'react-query/dist/react-query.production.min' {
  declare module.exports: any;
}

declare module 'react-query/es/core/config' {
  declare module.exports: any;
}

declare module 'react-query/es/core' {
  declare module.exports: any;
}

declare module 'react-query/es/core/notifyManager' {
  declare module.exports: any;
}

declare module 'react-query/es/core/query' {
  declare module.exports: any;
}

declare module 'react-query/es/core/queryCache' {
  declare module.exports: any;
}

declare module 'react-query/es/core/queryObserver' {
  declare module.exports: any;
}

declare module 'react-query/es/core/setFocusHandler' {
  declare module.exports: any;
}

declare module 'react-query/es/core/setOnlineHandler' {
  declare module.exports: any;
}

declare module 'react-query/es/core/types' {
  declare module.exports: any;
}

declare module 'react-query/es/core/utils' {
  declare module.exports: any;
}

declare module 'react-query/es/hydration/hydration' {
  declare module.exports: any;
}

declare module 'react-query/es/hydration' {
  declare module.exports: any;
}

declare module 'react-query/es/hydration/react' {
  declare module.exports: any;
}

declare module 'react-query/es' {
  declare module.exports: any;
}

declare module 'react-query/es/react' {
  declare module.exports: any;
}

declare module 'react-query/es/react/reactBatchedUpdates' {
  declare module.exports: any;
}

declare module 'react-query/es/react/reactBatchedUpdates.native' {
  declare module.exports: any;
}

declare module 'react-query/es/react/ReactQueryCacheProvider' {
  declare module.exports: any;
}

declare module 'react-query/es/react/ReactQueryConfigProvider' {
  declare module.exports: any;
}

declare module 'react-query/es/react/ReactQueryErrorResetBoundary' {
  declare module.exports: any;
}

declare module 'react-query/es/react/tests/utils' {
  declare module.exports: any;
}

declare module 'react-query/es/react/useBaseQuery' {
  declare module.exports: any;
}

declare module 'react-query/es/react/useInfiniteQuery' {
  declare module.exports: any;
}

declare module 'react-query/es/react/useIsFetching' {
  declare module.exports: any;
}

declare module 'react-query/es/react/useMutation' {
  declare module.exports: any;
}

declare module 'react-query/es/react/usePaginatedQuery' {
  declare module.exports: any;
}

declare module 'react-query/es/react/useQuery' {
  declare module.exports: any;
}

declare module 'react-query/es/react/utils' {
  declare module.exports: any;
}

declare module 'react-query/hydration' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/config' {
  declare module.exports: any;
}

declare module 'react-query/lib/core' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/notifyManager' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/query' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/queryCache' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/queryObserver' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/setFocusHandler' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/setOnlineHandler' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/types' {
  declare module.exports: any;
}

declare module 'react-query/lib/core/utils' {
  declare module.exports: any;
}

declare module 'react-query/lib/hydration/hydration' {
  declare module.exports: any;
}

declare module 'react-query/lib/hydration' {
  declare module.exports: any;
}

declare module 'react-query/lib/hydration/react' {
  declare module.exports: any;
}

declare module 'react-query/lib' {
  declare module.exports: any;
}

declare module 'react-query/lib/react' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/reactBatchedUpdates' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/reactBatchedUpdates.native' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/ReactQueryCacheProvider' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/ReactQueryConfigProvider' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/ReactQueryErrorResetBoundary' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/tests/utils' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/useBaseQuery' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/useInfiniteQuery' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/useIsFetching' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/useMutation' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/usePaginatedQuery' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/useQuery' {
  declare module.exports: any;
}

declare module 'react-query/lib/react/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-query/dist/hydration/react-query-hydration.development.js' {
  declare module.exports: $Exports<'react-query/dist/hydration/react-query-hydration.development'>;
}
declare module 'react-query/dist/hydration/react-query-hydration.production.min.js' {
  declare module.exports: $Exports<'react-query/dist/hydration/react-query-hydration.production.min'>;
}
declare module 'react-query/dist/react-query.development.js' {
  declare module.exports: $Exports<'react-query/dist/react-query.development'>;
}
declare module 'react-query/dist/react-query.production.min.js' {
  declare module.exports: $Exports<'react-query/dist/react-query.production.min'>;
}
declare module 'react-query/es/core/config.js' {
  declare module.exports: $Exports<'react-query/es/core/config'>;
}
declare module 'react-query/es/core/index' {
  declare module.exports: $Exports<'react-query/es/core'>;
}
declare module 'react-query/es/core/index.js' {
  declare module.exports: $Exports<'react-query/es/core'>;
}
declare module 'react-query/es/core/notifyManager.js' {
  declare module.exports: $Exports<'react-query/es/core/notifyManager'>;
}
declare module 'react-query/es/core/query.js' {
  declare module.exports: $Exports<'react-query/es/core/query'>;
}
declare module 'react-query/es/core/queryCache.js' {
  declare module.exports: $Exports<'react-query/es/core/queryCache'>;
}
declare module 'react-query/es/core/queryObserver.js' {
  declare module.exports: $Exports<'react-query/es/core/queryObserver'>;
}
declare module 'react-query/es/core/setFocusHandler.js' {
  declare module.exports: $Exports<'react-query/es/core/setFocusHandler'>;
}
declare module 'react-query/es/core/setOnlineHandler.js' {
  declare module.exports: $Exports<'react-query/es/core/setOnlineHandler'>;
}
declare module 'react-query/es/core/types.js' {
  declare module.exports: $Exports<'react-query/es/core/types'>;
}
declare module 'react-query/es/core/utils.js' {
  declare module.exports: $Exports<'react-query/es/core/utils'>;
}
declare module 'react-query/es/hydration/hydration.js' {
  declare module.exports: $Exports<'react-query/es/hydration/hydration'>;
}
declare module 'react-query/es/hydration/index' {
  declare module.exports: $Exports<'react-query/es/hydration'>;
}
declare module 'react-query/es/hydration/index.js' {
  declare module.exports: $Exports<'react-query/es/hydration'>;
}
declare module 'react-query/es/hydration/react.js' {
  declare module.exports: $Exports<'react-query/es/hydration/react'>;
}
declare module 'react-query/es/index' {
  declare module.exports: $Exports<'react-query/es'>;
}
declare module 'react-query/es/index.js' {
  declare module.exports: $Exports<'react-query/es'>;
}
declare module 'react-query/es/react/index' {
  declare module.exports: $Exports<'react-query/es/react'>;
}
declare module 'react-query/es/react/index.js' {
  declare module.exports: $Exports<'react-query/es/react'>;
}
declare module 'react-query/es/react/reactBatchedUpdates.js' {
  declare module.exports: $Exports<'react-query/es/react/reactBatchedUpdates'>;
}
declare module 'react-query/es/react/reactBatchedUpdates.native.js' {
  declare module.exports: $Exports<'react-query/es/react/reactBatchedUpdates.native'>;
}
declare module 'react-query/es/react/ReactQueryCacheProvider.js' {
  declare module.exports: $Exports<'react-query/es/react/ReactQueryCacheProvider'>;
}
declare module 'react-query/es/react/ReactQueryConfigProvider.js' {
  declare module.exports: $Exports<'react-query/es/react/ReactQueryConfigProvider'>;
}
declare module 'react-query/es/react/ReactQueryErrorResetBoundary.js' {
  declare module.exports: $Exports<'react-query/es/react/ReactQueryErrorResetBoundary'>;
}
declare module 'react-query/es/react/tests/utils.js' {
  declare module.exports: $Exports<'react-query/es/react/tests/utils'>;
}
declare module 'react-query/es/react/useBaseQuery.js' {
  declare module.exports: $Exports<'react-query/es/react/useBaseQuery'>;
}
declare module 'react-query/es/react/useInfiniteQuery.js' {
  declare module.exports: $Exports<'react-query/es/react/useInfiniteQuery'>;
}
declare module 'react-query/es/react/useIsFetching.js' {
  declare module.exports: $Exports<'react-query/es/react/useIsFetching'>;
}
declare module 'react-query/es/react/useMutation.js' {
  declare module.exports: $Exports<'react-query/es/react/useMutation'>;
}
declare module 'react-query/es/react/usePaginatedQuery.js' {
  declare module.exports: $Exports<'react-query/es/react/usePaginatedQuery'>;
}
declare module 'react-query/es/react/useQuery.js' {
  declare module.exports: $Exports<'react-query/es/react/useQuery'>;
}
declare module 'react-query/es/react/utils.js' {
  declare module.exports: $Exports<'react-query/es/react/utils'>;
}
declare module 'react-query/hydration.js' {
  declare module.exports: $Exports<'react-query/hydration'>;
}
declare module 'react-query/lib/core/config.js' {
  declare module.exports: $Exports<'react-query/lib/core/config'>;
}
declare module 'react-query/lib/core/index' {
  declare module.exports: $Exports<'react-query/lib/core'>;
}
declare module 'react-query/lib/core/index.js' {
  declare module.exports: $Exports<'react-query/lib/core'>;
}
declare module 'react-query/lib/core/notifyManager.js' {
  declare module.exports: $Exports<'react-query/lib/core/notifyManager'>;
}
declare module 'react-query/lib/core/query.js' {
  declare module.exports: $Exports<'react-query/lib/core/query'>;
}
declare module 'react-query/lib/core/queryCache.js' {
  declare module.exports: $Exports<'react-query/lib/core/queryCache'>;
}
declare module 'react-query/lib/core/queryObserver.js' {
  declare module.exports: $Exports<'react-query/lib/core/queryObserver'>;
}
declare module 'react-query/lib/core/setFocusHandler.js' {
  declare module.exports: $Exports<'react-query/lib/core/setFocusHandler'>;
}
declare module 'react-query/lib/core/setOnlineHandler.js' {
  declare module.exports: $Exports<'react-query/lib/core/setOnlineHandler'>;
}
declare module 'react-query/lib/core/types.js' {
  declare module.exports: $Exports<'react-query/lib/core/types'>;
}
declare module 'react-query/lib/core/utils.js' {
  declare module.exports: $Exports<'react-query/lib/core/utils'>;
}
declare module 'react-query/lib/hydration/hydration.js' {
  declare module.exports: $Exports<'react-query/lib/hydration/hydration'>;
}
declare module 'react-query/lib/hydration/index' {
  declare module.exports: $Exports<'react-query/lib/hydration'>;
}
declare module 'react-query/lib/hydration/index.js' {
  declare module.exports: $Exports<'react-query/lib/hydration'>;
}
declare module 'react-query/lib/hydration/react.js' {
  declare module.exports: $Exports<'react-query/lib/hydration/react'>;
}
declare module 'react-query/lib/index' {
  declare module.exports: $Exports<'react-query/lib'>;
}
declare module 'react-query/lib/index.js' {
  declare module.exports: $Exports<'react-query/lib'>;
}
declare module 'react-query/lib/react/index' {
  declare module.exports: $Exports<'react-query/lib/react'>;
}
declare module 'react-query/lib/react/index.js' {
  declare module.exports: $Exports<'react-query/lib/react'>;
}
declare module 'react-query/lib/react/reactBatchedUpdates.js' {
  declare module.exports: $Exports<'react-query/lib/react/reactBatchedUpdates'>;
}
declare module 'react-query/lib/react/reactBatchedUpdates.native.js' {
  declare module.exports: $Exports<'react-query/lib/react/reactBatchedUpdates.native'>;
}
declare module 'react-query/lib/react/ReactQueryCacheProvider.js' {
  declare module.exports: $Exports<'react-query/lib/react/ReactQueryCacheProvider'>;
}
declare module 'react-query/lib/react/ReactQueryConfigProvider.js' {
  declare module.exports: $Exports<'react-query/lib/react/ReactQueryConfigProvider'>;
}
declare module 'react-query/lib/react/ReactQueryErrorResetBoundary.js' {
  declare module.exports: $Exports<'react-query/lib/react/ReactQueryErrorResetBoundary'>;
}
declare module 'react-query/lib/react/tests/utils.js' {
  declare module.exports: $Exports<'react-query/lib/react/tests/utils'>;
}
declare module 'react-query/lib/react/useBaseQuery.js' {
  declare module.exports: $Exports<'react-query/lib/react/useBaseQuery'>;
}
declare module 'react-query/lib/react/useInfiniteQuery.js' {
  declare module.exports: $Exports<'react-query/lib/react/useInfiniteQuery'>;
}
declare module 'react-query/lib/react/useIsFetching.js' {
  declare module.exports: $Exports<'react-query/lib/react/useIsFetching'>;
}
declare module 'react-query/lib/react/useMutation.js' {
  declare module.exports: $Exports<'react-query/lib/react/useMutation'>;
}
declare module 'react-query/lib/react/usePaginatedQuery.js' {
  declare module.exports: $Exports<'react-query/lib/react/usePaginatedQuery'>;
}
declare module 'react-query/lib/react/useQuery.js' {
  declare module.exports: $Exports<'react-query/lib/react/useQuery'>;
}
declare module 'react-query/lib/react/utils.js' {
  declare module.exports: $Exports<'react-query/lib/react/utils'>;
}
